Initial
codex-team/codex.misprints pull request #2
Opened 2019-02-27 18:43 UTC by DorofeevMark

Issue - https://github.com/codex-team/codex.misprints/issues/1

2019-02-28 05:28 UTC, neSpecc requested changes

2019-02-28 05:28 UTC, neSpecc commented on src/service/index.ts
> +      message: `Url: ${window.location.href}, Title: ${document.title}, Top: ${topPosition}, Left: ${leftPosition}`
тут надо как-то оформить сообщение + не хватает самого выделенного фрагмента.

```
💌 Misprint

Selected text fragment

[New Block Tools API](https://editorjs.io/creating-a-block-tool) 
```

2019-02-28 19:25 UTC, kabachook commented on src/service/index.ts
> +    const params = Service.standardizeParams({
Зачем урлэнкодить в пост запросе?

2019-02-28 19:44 UTC, gohabereg requested changes
Обычно в таких модулях выскакивает попап с возможностью добавить коммент. Нам бы тоже не помешало

2019-02-28 19:44 UTC, gohabereg commented on package.json
> +  "name": "@codexteam/codex.misprints",
Просто @codexteam/misprints

2019-02-28 19:44 UTC, gohabereg commented on src/MisprintsModule.ts
> +   * @param {string} config.chatId - chat's identifier.
Не очень понятно, что за чат. Лучше поподробнее описать

2019-02-28 19:44 UTC, gohabereg commented on src/MisprintsModule.ts
> +        Service.notify(this.chatId, selection.toString(), fragmentPosition.top, fragmentPosition.left);
После const надо бы пустую строку

2019-02-28 19:44 UTC, gohabereg commented on src/service/index.ts
> +  private static notificationEndpoint = 'https://notify.bot.ifmo.su/u';
Лучше из конфига какого-нибудь брать, наверное

2019-02-28 19:44 UTC, gohabereg commented on src/service/index.ts
> +    const params = Service.standardizeParams({
Согласен, через formdata должно нормально отработать

2019-02-28 19:44 UTC, gohabereg commented on src/service/index.ts
> +  public static async notify (chatId: string, text: string, topPosition: number, leftPosition: number) {
Не пойму зачем координаты

2019-03-02 16:53 UTC, DorofeevMark commented on src/service/index.ts
> +    const params = Service.standardizeParams({
с другим сontent-type не работает

2019-03-04 05:08 UTC, neSpecc approved these changes

2019-03-04 07:17 UTC, talyguryn requested changes
также нужно добавить .npmignore

2019-03-04 07:17 UTC, talyguryn commented on package.json
> +  "main": "dist/codex.misprints.js",
```suggestion
  "main": "dist/misprints.js",
```

2019-03-04 07:17 UTC, talyguryn commented on package.json
> +    "url": "https://ifmo.su"
```suggestion
    "url": "https://codex.so"
```

2019-03-04 07:17 UTC, talyguryn commented on package.json
> +  "dependencies": {
```suggestion
```

2019-03-04 07:17 UTC, talyguryn commented on package.json
> +  }
```suggestion
```

2019-03-04 07:17 UTC, talyguryn commented on src/MisprintsModule.ts
> +    this.chatId = config.chatId;
стоит оставить возможность вводить любой вебхук без привязки к нашему боту, а не просто айди чата

2019-03-04 07:17 UTC, talyguryn commented on example/example.html
> +<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit. Accusamus, accusantium commodi debitis dolor doloremque
можно сюда вставить немного осмысленный текст, хотя бы с описанием модуля и его работы?

2019-03-04 07:17 UTC, talyguryn commented on src/MisprintsModule.ts
> +  constructor (config: MisprintsConfig) {
нет ли смысла в консоли выведи сообщение, что активирован модуль опечаток и им можно воспользоваться по enter+shift?

2019-03-04 07:17 UTC, talyguryn commented on src/service/index.ts
> +const notificationEndpoint = 'https://notify.bot.ifmo.su/u';
предлагаю не зашивать адрес

2019-03-04 07:17 UTC, talyguryn commented on src/service/index.ts
> +    const params = Service.standardizeParams({
нужно добавить параметр `parse_mode: 'Markdown'`

2019-03-04 07:17 UTC, talyguryn commented on src/service/index.ts
> +      message: `💌 Misprint
```message: `💌 Misprint\n${text}\n${document.title} — ${window.location.href}`,```

2019-03-04 08:19 UTC, talyguryn requested changes
обновить ридми

2019-03-04 15:44 UTC, neSpecc commented on src/service/index.ts
> +      message: `💌 Misprint
тайтл должен быть ссылкой

2019-03-04 15:45 UTC, talyguryn commented on src/service/index.ts
> +      message: `💌 Misprint
ну как минимум добавить \n

2019-03-04 15:50 UTC, khaydarov commented on src/MisprintsModule.ts
> +  constructor (config: MisprintsConfig) {
тогда имеет смысл назвать не chatId, а просто webhook. Это класс будет абстрактным, а от него можем отнаследоваться и в слек также отправлять

2019-03-05 05:49 UTC, DorofeevMark commented on src/service/index.ts
> +    const params = Service.standardizeParams({
с ним не работает. Дефолтный parse_mode: 'HTML'

2019-03-05 06:04 UTC, neSpecc commented on src/MisprintsModule.ts
> +  constructor (config: MisprintsConfig) {
@talyguryn консоль — не подходящее для этого место, пользователи не знают о ее существовании. Это надо в интерфейсе сайта указывать где-то. Предлагаю оставить это на тех, кто будет подключать модуль.

2019-03-05 06:04 UTC, neSpecc commented on src/MisprintsModule.ts
> +    this.chatId = config.chatId;
создай issue

2019-03-05 06:10 UTC, neSpecc requested changes

2019-03-05 06:10 UTC, neSpecc commented on src/MisprintsModule.ts
> +        Service.notify(this.chatId, selection.toString());
надо как-то отреагировать в интерфейсе, чтобы было понятно, что все отправилось. Как временное решение предлагаю снимать выделение с фрагмента. Потом добавим красивое сообщение.

2019-03-05 06:10 UTC, neSpecc commented on README.md
> +### Initialization
еще нужен пункт про установку из npm/yarn

2019-03-05 06:10 UTC, neSpecc commented on src/service/index.ts
> +      message: `💌 Misprint\n${text}\n[${document.title}] (${window.location.href})`
не лишний пробел перед круглыми скобками?

2019-03-05 06:10 UTC, neSpecc commented on src/service/index.ts
> +    const response = await fetch(`${notificationEndpoint}/${chatId}`, {
реджект этого промиса нигде не обрабатывается. Возможно сам вызов notify стоит обернуть в try

2019-03-05 06:19 UTC, DorofeevMark commented on src/MisprintsModule.ts
> +        Service.notify(this.chatId, selection.toString());
Думаю будет лучше добавить два колбека в конфиг - один на резолв и один на реджект. Каждый сможет сам решать, как это обрабатывать

2019-03-12 11:32 UTC, neSpecc approved these changes

2019-03-12 12:00 UTC, talyguryn approved these changes

2019-03-12 12:02 UTC, gohabereg approved these changes

2019-03-12 12:37 UTC, merged