Added trimming for message
codex-team/codex.misprints pull request #9
Opened 2019-03-19 03:46 UTC by DorofeevMark

Resolves https://github.com/codex-team/codex.misprints/issues/4

2019-03-20 05:16 UTC, khaydarov requested changes

2019-03-20 05:16 UTC, khaydarov commented on src/service/index.ts
> +    text = text.length > 200 ? text.slice(0, 199) + '...' : text;
вынеси плиз 200 в константу MAX_TEXT_LENGTH какой-нибудь

2019-03-28 05:07 UTC, neSpecc approved these changes

2019-03-28 06:36 UTC, talyguryn approved these changes

2019-03-29 04:07 UTC, merged